server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://43.200.3.134:3306/gstock?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: awskjh
    password: 7193asd
  servlet:
    multipart:
      enabled: true
      location: /home/upload/
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  config:
    import: "optional:key.yml"
    
      
mybatis:
  mapper-locations:
  - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.green.greenstock.repository.model
   



#logging:
#  level:
#    '[org.mybatis]': DEBUG
